import { TextField } from "@mui/material";
import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { useRecoilState } from "recoil";
import Contact from "../components/home/Contact";
import Hero from "../components/home/Hero";
import Skills from "../components/home/Skills";
import Work, { ProjectType } from "../components/home/Work";
import { ProjectsState } from "../state/recoil/projects";

const Home: NextPage<{ projects: ProjectType[] }> = ({ projects }) => {
  return (
    <main className="flex flex-col gap-24 mb-24 pt-20">
      <Head>
        <title>Kerlos</title>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Skills />
      <Work projects={projects} />
      <Contact />
    </main>
  );
};

export default Home;

export const getServerSideProps = async () => {
  const { data } = await axios("http://localhost:3000/api/projects");
  return {
    props: { projects: data },
  };
};
